### ISSUE TITLE
UML

### ISSUE THREAD

**Issue by mariela21180** [mariela21180/institucional-cfp#1]

**Comment by OzielSpathe** [comment]
Hoy modificamos el UML con respecto al HTML.

**Comment by mariela21180** [comment]
Version de hoy:

![UML](https://user-images.githubusercontent.com/3533830/68907497-c1374d00-0726-11ea-9c95-63a0ca5e6c60.png)

**Comment by mariela21180** [comment]
Version de hoy:

![diagrama_proyecto_final](https://user-images.githubusercontent.com/3533830/69195667-18fcfc00-0b0b-11ea-83c8-2b4c502be345.png)

**Comment by mariela21180** [comment]
Ultima version de hoy:

![diagrama_proyecto_final](https://user-images.githubusercontent.com/3533830/69204775-aa2d9c00-0b26-11ea-89cf-bf9e51f7b119.png)

**Comment by juansalerno** [comment]
UML final
![diagrama_proyecto_final](https://user-images.githubusercontent.com/52261724/69685932-e28c2780-109c-11ea-9953-8126550c5103.png)
