### ISSUE TITLE
Mockups del HTML

### ISSUE THREAD

**Issue by OzielSpathe** [mariela21180/institucional-cfp#3]
Esta taréa es para trabajar los borradores de las vistas del front.

- [x] 1) Formularios

- [x] 2) Crear Examen (el examen creado se re-usa también para responder y para calificar)

- [x] 3) Crear Curso

- [x] 4) Crear Alumno (Inscripciones)

- [x] 5) Cargar Asistencia (lista de clases ya creadas de todos los cursos, para editar la asistencia en una existente o crear nueva clase)

- [x] 6 ) Crear Profesor

- [x] 7) En Curso, cambiar 3 campos "Fecha" + "Hora inicio"/"Hora fin" por 2 campos Inicio/Fin  con datetimepicker en ambos. Ver por ejemplo: https://tempusdominus.github.io/bootstrap-4/Options/ (version actualizada)

- [x] 8) Hacer vista de Login

**Comment by OzielSpathe** [comment]
Hoy hicimos la difinicion de la clase Formulario y clase FormularioExamen

**Comment by mariela21180** [comment]
1 ) 
![image](https://user-images.githubusercontent.com/3533830/68729007-94a8f700-05a7-11ea-8cb8-a4e986f7521c.png)

**Comment by mariela21180** [comment]
2 ) 
![image](https://user-images.githubusercontent.com/3533830/68729033-a7bbc700-05a7-11ea-9237-ee6793119bf2.png)

**Comment by mariela21180** [comment]
3 )  
![image](https://user-images.githubusercontent.com/3533830/68907575-1a06e580-0727-11ea-9af1-ba88fb93b749.png)

![image](https://user-images.githubusercontent.com/3533830/68907601-2f7c0f80-0727-11ea-9afe-3b2c6e67d47b.png)

**Comment by OzielSpathe** [comment]
Hoy con Agustina empezamos a crear el diseño de la pagina web y el formulario
