### ISSUE TITLE
Back-end - Clases

### ISSUE THREAD

**Issue by juansalerno** [mariela21180/institucional-cfp#9]
Confección del back-end y clases mediante proyecto Nest

**Curso:** @juansalerno @mariela21180 
- [x] 1) Material
- [x] 2) Curso
- [x] 3) Horario
- [x] 4) Clase

**Formulario:** @mariela21180 
- [x] 1) Respuesta
- [x] 2) Pregunta
- [x] 3) TipoPregunta (enum)
- [x] 4) Formulario
- [x] 5) Examen

**Persona:** @juansalerno 
- [x] 1) Persona
- [x] 2) Docente
- [x] 3) Usuario
- [x] 4) Alumno
- [x] 5) Telefono
- [x] 6) Domicilio

**Comment by mariela21180** [comment]
@juansalerno ya creé todas las clases de Formulario, pero necesitaría terminemos de revisar juntos los métodos (principamente de Examen).
Si tenés tiempo mira lo hecho a ver si algo cambiarías, pero no hice mucho mas que getters y setters básicamente, y el constructor con los atributos que me parecía debían ser opcionales (a debatir).

De Curso sólo creé la clase Curso como para poder importarle, pero está vacía aún, sólo la declaré.


De Persona chusmeé un poquito por arriba lo tuyo, y lo unico que noté que no me parece necesario es el método cambiarEstadoDocumentacion() - Para mi con simplemente poner un setEstadoDocumentacion() alcanza. 
![image](https://user-images.githubusercontent.com/3533830/69204562-004e0f80-0b26-11ea-90cf-c43698e4784a.png)


Nos vemos mañana!
